name: Renovate
on:
  workflow_dispatch:
  #schedule:
    # The "*" (#42, asterisk) character has special semantics in YAML, so this
    # string has to be quoted.
    #- cron: "*/15 * * * *"
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Get token
        id: get_token
        uses: actions/create-github-app-token@v3.2.0
        with:
          private-key: ${{ secrets.RENOVATE_PRIVATE_KEY }}
          client-id: ${{ secrets.CLIENT_ID }}
          owner: ${{ github.repository_owner }}
          repositories: "anseliv/OmegaClaw-Core"

      - name: Checkout
        uses: actions/checkout@v6.0.3

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v46.1.18
        env: 
          LOG_LEVEL: debug
        with:
          configurationFile: .github/renovate-config.js
          token: "${{ steps.get_token.outputs.token }}"
